name: Build

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  cancel:
    name: "Cancel previous workflow runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: build.yaml
          access_token: ${{ github.token }}

  build:
    name: "Build kernel artifacts"
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ github.token }}
      - name: Build kernel artifacts
        run: |
          earthly +build --KERNEL_VERSION=$KERNEL_VERSION
        env:
          KERNEL_VERSION: "${{ github.ref_name }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: false
          files: RPMS/${{ github.ref_name }}/**
